-- ============================================================================
-- စပါးအောင်သွယ် — Township Seed Data
-- Run this AFTER schema.sql in Supabase Dashboard → SQL Editor
-- Region IDs 1-15 are already seeded by schema.sql
-- ============================================================================

-- Yangon Region (id=15)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Ahlon","my":"အလုံ"}', 15, 1),
  ('{"en":"Bahan","my":"ဗဟန်း"}', 15, 2),
  ('{"en":"Botahtaung","my":"ဗိုလ်တထောင်"}', 15, 3),
  ('{"en":"Dagon","my":"ဒဂုံ"}', 15, 4),
  ('{"en":"Dagon Myothit (East)","my":"ဒဂုံမြို့သစ်(အရှေ့ပိုင်း)"}', 15, 5),
  ('{"en":"Dagon Myothit (North)","my":"ဒဂုံမြို့သစ်(မြောက်ပိုင်း)"}', 15, 6),
  ('{"en":"Dagon Myothit (South)","my":"ဒဂုံမြို့သစ်(တောင်ပိုင်း)"}', 15, 7),
  ('{"en":"Dagon Myothit (Seikkan)","my":"ဒဂုံမြို့သစ်(ဆိပ်ကမ်း)"}', 15, 8),
  ('{"en":"Dala","my":"ဒလ"}', 15, 9),
  ('{"en":"Dawbon","my":"ဒေါပုံ"}', 15, 10),
  ('{"en":"Hlaing","my":"လှိုင်"}', 15, 11),
  ('{"en":"Hlaingthaya","my":"လှိုင်သာယာ"}', 15, 12),
  ('{"en":"Hlegu","my":"လှည်းကူး"}', 15, 13),
  ('{"en":"Hmawbi","my":"မှော်ဘီ"}', 15, 14),
  ('{"en":"Htantabin","my":"ထန်းတပင်"}', 15, 15),
  ('{"en":"Insein","my":"အင်းစိန်"}', 15, 16),
  ('{"en":"Kamayut","my":"ကမာရွတ်"}', 15, 17),
  ('{"en":"Kawhmu","my":"ကော့မှူး"}', 15, 18),
  ('{"en":"Khayan","my":"ခရမ်း"}', 15, 19),
  ('{"en":"Kungyangon","my":"ကွမ်းခြံကုန်း"}', 15, 20),
  ('{"en":"Kyauktada","my":"ကျောက်တံတား"}', 15, 21),
  ('{"en":"Kyauktan","my":"ကျောက်တန်း"}', 15, 22),
  ('{"en":"Kyeemyindaing","my":"ကြည့်မြင်တိုင်"}', 15, 23),
  ('{"en":"Lanmadaw","my":"လမ်းမတော်"}', 15, 24),
  ('{"en":"Latha","my":"လသာ"}', 15, 25),
  ('{"en":"Mayangone","my":"မရမ်းကုန်း"}', 15, 26),
  ('{"en":"Mingaladon","my":"မင်္ဂလာဒုံ"}', 15, 27),
  ('{"en":"Mingalartaungnyunt","my":"မင်္ဂလာတောင်ညွန့်"}', 15, 28),
  ('{"en":"North Okkalapa","my":"မြောက်ဥက္ကလာပ"}', 15, 29),
  ('{"en":"Pabedan","my":"ပန်းဘဲတန်း"}', 15, 30),
  ('{"en":"Pazundaung","my":"ပုဇွန်တောင်"}', 15, 31),
  ('{"en":"Sanchaung","my":"စမ်းချောင်း"}', 15, 32),
  ('{"en":"Seikgyikanaungto","my":"ဆိပ်ကြီးခနောင်တို"}', 15, 33),
  ('{"en":"Seikkan","my":"ဆိပ်ကမ်း"}', 15, 34),
  ('{"en":"Shwepyitha","my":"ရွှေပြည်သာ"}', 15, 35),
  ('{"en":"South Okkalapa","my":"တောင်ဥက္ကလာပ"}', 15, 36),
  ('{"en":"Taikkyi","my":"တိုက်ကြီး"}', 15, 37),
  ('{"en":"Tamwe","my":"တာမွေ"}', 15, 38),
  ('{"en":"Thaketa","my":"သာကေတ"}', 15, 39),
  ('{"en":"Thanlyin","my":"သန်လျင်"}', 15, 40),
  ('{"en":"Thingangyun","my":"သင်္ဃန်းကျွန်း"}', 15, 41),
  ('{"en":"Thongwa","my":"သုံးခွ"}', 15, 42),
  ('{"en":"Twantay","my":"တွံတေး"}', 15, 43),
  ('{"en":"Yankin","my":"ရန်ကင်း"}', 15, 44);

-- Mandalay Region (id=8)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Amarapura","my":"အမရပူရ"}', 8, 1),
  ('{"en":"Aungmyethazan","my":"အောင်မြေသာစံ"}', 8, 2),
  ('{"en":"Chanayethazan","my":"ချမ်းအေးသာစံ"}', 8, 3),
  ('{"en":"Chanmyathazi","my":"ချမ်းမြသာစည်"}', 8, 4),
  ('{"en":"Kyaukpadaung","my":"ကျောက်ပန်းတောင်း"}', 8, 5),
  ('{"en":"Kyaukse","my":"ကျောက်ဆည်"}', 8, 6),
  ('{"en":"Lewe","my":"လယ်ဝေး"}', 8, 7),
  ('{"en":"Madaya","my":"မတ္တရာ"}', 8, 8),
  ('{"en":"Mahaaungmyay","my":"မဟာအောင်မြေ"}', 8, 9),
  ('{"en":"Mahlaing","my":"မလှိုင်"}', 8, 10),
  ('{"en":"Meiktila","my":"မိတ္ထီလာ"}', 8, 11),
  ('{"en":"Mogok","my":"မိုးကုတ်"}', 8, 12),
  ('{"en":"Myingyan","my":"မြင်းခြံ"}', 8, 13),
  ('{"en":"Myittha","my":"မြစ်သား"}', 8, 14),
  ('{"en":"Natogyi","my":"နွားထိုးကြီး"}', 8, 15),
  ('{"en":"Ngazun","my":"ငါန်းဇွန်"}', 8, 16),
  ('{"en":"Nyaung-U","my":"ညောင်ဦး"}', 8, 17),
  ('{"en":"Patheingyi","my":"ပုသိမ်ကြီး"}', 8, 18),
  ('{"en":"Pyawbwe","my":"ပျော်ဘွယ်"}', 8, 19),
  ('{"en":"Pyigyidagun","my":"ပြည်ကြီးတံခွန်"}', 8, 20),
  ('{"en":"Pyinoolwin","my":"ပြင်ဦးလွင်"}', 8, 21),
  ('{"en":"Singu","my":"စဉ့်ကူး"}', 8, 22),
  ('{"en":"Sintgaing","my":"စဉ့်ကိုင်"}', 8, 23),
  ('{"en":"Tada-U","my":"တံတားဦး"}', 8, 24),
  ('{"en":"Taungtha","my":"တောင်သာ"}', 8, 25),
  ('{"en":"Thabeikkyin","my":"သပိတ်ကျင်း"}', 8, 26),
  ('{"en":"Thazi","my":"သာစည်"}', 8, 27),
  ('{"en":"Wundwin","my":"ဝမ်းတွင်း"}', 8, 28),
  ('{"en":"Yamethin","my":"ရမည်းသင်း"}', 8, 29);

-- Ayeyarwady Region (id=1)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Bogale","my":"ဘိုကလေး"}', 1, 1),
  ('{"en":"Danubyu","my":"ဓနုဖြူ"}', 1, 2),
  ('{"en":"Dedaye","my":"ဒေးဒရဲ"}', 1, 3),
  ('{"en":"Einme","my":"အိမ်မဲ"}', 1, 4),
  ('{"en":"Hinthada","my":"ဟင်္သာတ"}', 1, 5),
  ('{"en":"Ingapu","my":"အင်္ဂပူ"}', 1, 6),
  ('{"en":"Kangyidaunt","my":"ကံကြီးဒေါင့်"}', 1, 7),
  ('{"en":"Kyaiklat","my":"ကျိုက်လတ်"}', 1, 8),
  ('{"en":"Kyangin","my":"ကြံခင်း"}', 1, 9),
  ('{"en":"Kyaunggon","my":"ကျောင်းကုန်း"}', 1, 10),
  ('{"en":"Kyonpyaw","my":"ကျုံပျော်"}', 1, 11),
  ('{"en":"Labutta","my":"လပွတ္တာ"}', 1, 12),
  ('{"en":"Lemyethna","my":"လေးမျက်နှာ"}', 1, 13),
  ('{"en":"Maubin","my":"မအူပင်"}', 1, 14),
  ('{"en":"Mawlamyinegyun","my":"မော်လမြိုင်ကျွန်း"}', 1, 15),
  ('{"en":"Myanaung","my":"မြန်အောင်"}', 1, 16),
  ('{"en":"Myaungmya","my":"မြောင်းမြ"}', 1, 17),
  ('{"en":"Ngapudaw","my":"ငပုတော"}', 1, 18),
  ('{"en":"Nyaungdon","my":"ညောင်တုန်း"}', 1, 19),
  ('{"en":"Pantanaw","my":"ပန်းတနော်"}', 1, 20),
  ('{"en":"Pathein","my":"ပုသိမ်"}', 1, 21),
  ('{"en":"Pyapon","my":"ဖျာပုံ"}', 1, 22),
  ('{"en":"Thabaung","my":"သာပေါင်း"}', 1, 23),
  ('{"en":"Wakema","my":"ဝါးခယ်မ"}', 1, 24),
  ('{"en":"Yegyi","my":"ရေကြည်"}', 1, 25),
  ('{"en":"Zalun","my":"ဇလွန်"}', 1, 26);

-- Sagaing Region (id=12)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Ayadaw","my":"အရာတော်"}', 12, 1),
  ('{"en":"Banmauk","my":"ဗန်းမောက်"}', 12, 2),
  ('{"en":"Budalin","my":"ဘုတလင်"}', 12, 3),
  ('{"en":"Chaung-U","my":"ချောင်းဦး"}', 12, 4),
  ('{"en":"Hkamti","my":"ခန္တီး"}', 12, 5),
  ('{"en":"Homalin","my":"ဟုမ္မလင်း"}', 12, 6),
  ('{"en":"Indaw","my":"အင်းတော်"}', 12, 7),
  ('{"en":"Kale","my":"ကလေး"}', 12, 8),
  ('{"en":"Kalewa","my":"ကလေးဝ"}', 12, 9),
  ('{"en":"Kanbalu","my":"ကန့်ဘလူ"}', 12, 10),
  ('{"en":"Katha","my":"ကသာ"}', 12, 11),
  ('{"en":"Kawlin","my":"ကောလင်း"}', 12, 12),
  ('{"en":"Khin-U","my":"ခင်ဦး"}', 12, 13),
  ('{"en":"Lahe","my":"လဟယ်"}', 12, 14),
  ('{"en":"Leshi","my":"လေရှီး"}', 12, 15),
  ('{"en":"Mawlaik","my":"မော်လိုက်"}', 12, 16),
  ('{"en":"Mingin","my":"မင်းကင်း"}', 12, 17),
  ('{"en":"Monywa","my":"မုံရွာ"}', 12, 18),
  ('{"en":"Myaung","my":"မြောင်"}', 12, 19),
  ('{"en":"Myinmu","my":"မြင်းမူ"}', 12, 20),
  ('{"en":"Nanyun","my":"နန်းယွန်း"}', 12, 21),
  ('{"en":"Pale","my":"ပုလဲ"}', 12, 22),
  ('{"en":"Paungbyin","my":"ဖောင်းပြင်"}', 12, 23),
  ('{"en":"Pinlebu","my":"ပင်လယ်ဘူး"}', 12, 24),
  ('{"en":"Sagaing","my":"စစ်ကိုင်း"}', 12, 25),
  ('{"en":"Salingyi","my":"စလင်းကြီး"}', 12, 26),
  ('{"en":"Shwebo","my":"ရွှေဘို"}', 12, 27),
  ('{"en":"Tamu","my":"တမူး"}', 12, 28),
  ('{"en":"Taze","my":"တန့်ဆည်"}', 12, 29),
  ('{"en":"Tigyaing","my":"ထီးချိုင့်"}', 12, 30),
  ('{"en":"Wetlet","my":"ဝက်လက်"}', 12, 31),
  ('{"en":"Wuntho","my":"ဝန်းသို"}', 12, 32),
  ('{"en":"Ye-U","my":"ရေဦး"}', 12, 33),
  ('{"en":"Yinmarbin","my":"�င်းမာပင်"}', 12, 34);

-- Bago Region (id=2)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Bago","my":"ပဲခူး"}', 2, 1),
  ('{"en":"Daik-U","my":"ဒိုက်ဦး"}', 2, 2),
  ('{"en":"Gyobingauk","my":"ကြို့ပင်ကောက်"}', 2, 3),
  ('{"en":"Kawa","my":"ကဝ"}', 2, 4),
  ('{"en":"Kyauktaga","my":"ကျောက်တံခါး"}', 2, 5),
  ('{"en":"Letpadan","my":"လက်ပံတန်း"}', 2, 6),
  ('{"en":"Minhla","my":"မင်းလှ"}', 2, 7),
  ('{"en":"Monyo","my":"မိုးညို"}', 2, 8),
  ('{"en":"Nattalin","my":"နတ်တလင်း"}', 2, 9),
  ('{"en":"Nyaunglebin","my":"ညောင်လေးပင်"}', 2, 10),
  ('{"en":"Oktwin","my":"အုတ်တွင်း"}', 2, 11),
  ('{"en":"Padaung","my":"ပန်းတောင်း"}', 2, 12),
  ('{"en":"Paukkaung","my":"ပေါက်ခေါင်း"}', 2, 13),
  ('{"en":"Paungde","my":"ပေါင်းတည်"}', 2, 14),
  ('{"en":"Pyay","my":"ပြည်"}', 2, 15),
  ('{"en":"Shwegyin","my":"ရွှေကျင်"}', 2, 16),
  ('{"en":"Shwedaung","my":"ရွှေတောင်"}', 2, 17),
  ('{"en":"Tantabin","my":"တန်တပင်"}', 2, 18),
  ('{"en":"Taungoo","my":"တောင်ငူ"}', 2, 19),
  ('{"en":"Thanatpin","my":"သနပ်ပင်"}', 2, 20),
  ('{"en":"Thegon","my":"သဲကုန်း"}', 2, 21),
  ('{"en":"Thayarwady","my":"သာယာဝတီ"}', 2, 22),
  ('{"en":"Waw","my":"ဝေါ"}', 2, 23),
  ('{"en":"Yedashe","my":"ရေတာရှည်"}', 2, 24),
  ('{"en":"Zigon","my":"ဇီးကုန်း"}', 2, 25);

-- Magway Region (id=7)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Aunglan","my":"အောင်လံ"}', 7, 1),
  ('{"en":"Chauk","my":"ချောက်"}', 7, 2),
  ('{"en":"Gangaw","my":"ဂန့်ဂေါ"}', 7, 3),
  ('{"en":"Kamma","my":"ကံမ"}', 7, 4),
  ('{"en":"Magway","my":"မကွေး"}', 7, 5),
  ('{"en":"Minbu","my":"မင်းဘူး"}', 7, 6),
  ('{"en":"Mindon","my":"မင်းတုန်း"}', 7, 7),
  ('{"en":"Minhla","my":"မင်းလှ"}', 7, 8),
  ('{"en":"Myaing","my":"မြိုင်"}', 7, 9),
  ('{"en":"Myothit","my":"မြို့သစ်"}', 7, 10),
  ('{"en":"Natmauk","my":"နတ်မောက်"}', 7, 11),
  ('{"en":"Ngaphe","my":"ငဖဲ"}', 7, 12),
  ('{"en":"Pakokku","my":"ပခုက္ကူ"}', 7, 13),
  ('{"en":"Pauk","my":"ပေါက်"}', 7, 14),
  ('{"en":"Pwintbyu","my":"ပွင့်ဖြူ"}', 7, 15),
  ('{"en":"Salin","my":"စလင်း"}', 7, 16),
  ('{"en":"Saw","my":"ဆော"}', 7, 17),
  ('{"en":"Seikphyu","my":"ဆိပ်ဖြူ"}', 7, 18),
  ('{"en":"Sidoktaya","my":"စေတုတ္တရာ"}', 7, 19),
  ('{"en":"Sinbyugyun","my":"ဆင်ဖြူကျွန်း"}', 7, 20),
  ('{"en":"Taungdwingyi","my":"တောင်တွင်းကြီး"}', 7, 21),
  ('{"en":"Thayet","my":"သရက်"}', 7, 22),
  ('{"en":"Tilin","my":"ထီးလင်း"}', 7, 23),
  ('{"en":"Yenangyaung","my":"ရေနံချောင်း"}', 7, 24),
  ('{"en":"Yesagyo","my":"ရေစကြို"}', 7, 25);

-- Tanintharyi Region (id=14)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Bokpyin","my":"ဘုတ်ပြင်း"}', 14, 1),
  ('{"en":"Dawei","my":"ထားဝယ်"}', 14, 2),
  ('{"en":"Kawthoung","my":"ကော့သောင်း"}', 14, 3),
  ('{"en":"Kyunsu","my":"ကျွန်းစု"}', 14, 4),
  ('{"en":"Launglon","my":"လောင်းလုံ"}', 14, 5),
  ('{"en":"Myeik","my":"မြိတ်"}', 14, 6),
  ('{"en":"Palaw","my":"ပုလော"}', 14, 7),
  ('{"en":"Tanintharyi","my":"တနင်္သာရီ"}', 14, 8),
  ('{"en":"Thayetchaung","my":"သရက်ချောင်း"}', 14, 9),
  ('{"en":"Yebyu","my":"ရေဖြူ"}', 14, 10);

-- Kachin State (id=4)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Bhamo","my":"ဗန်းမော်"}', 4, 1),
  ('{"en":"Chipwi","my":"ချီဖွေ"}', 4, 2),
  ('{"en":"Hpakant","my":"ဖားကန့်"}', 4, 3),
  ('{"en":"Injangyang","my":"အင်ဂျန်းယန်"}', 4, 4),
  ('{"en":"Kawnglanghpu","my":"ခေါင်လန်ဖူး"}', 4, 5),
  ('{"en":"Machanbaw","my":"မချမ်းဘော"}', 4, 6),
  ('{"en":"Mansi","my":"မန်စီ"}', 4, 7),
  ('{"en":"Mogaung","my":"မိုးကောင်း"}', 4, 8),
  ('{"en":"Mohnyin","my":"မိုးညှင်း"}', 4, 9),
  ('{"en":"Momauk","my":"မိုးမောက်"}', 4, 10),
  ('{"en":"Myitkyina","my":"မြစ်ကြီးနား"}', 4, 11),
  ('{"en":"Nogmung","my":"နောင်မွန်း"}', 4, 12),
  ('{"en":"Puta-O","my":"ပူတာအို"}', 4, 13),
  ('{"en":"Shwegu","my":"ရွှေကူ"}', 4, 14),
  ('{"en":"Sumprabum","my":"ဆွမ်ပရာဘွမ်"}', 4, 15),
  ('{"en":"Tanai","my":"တနိုင်း"}', 4, 16),
  ('{"en":"Tsawlaw","my":"ဆော့လော်"}', 4, 17),
  ('{"en":"Waingmaw","my":"ဝိုင်းမော်"}', 4, 18);

-- Kayah State (id=5)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Bawlakhe","my":"ဘော်လခဲ"}', 5, 1),
  ('{"en":"Demoso","my":"ဒီးမော့ဆို"}', 5, 2),
  ('{"en":"Hpasawng","my":"ဖားဆောင်း"}', 5, 3),
  ('{"en":"Hpruso","my":"ဖရူဆို"}', 5, 4),
  ('{"en":"Loikaw","my":"လွိုင်ကော်"}', 5, 5),
  ('{"en":"Mese","my":"မယ်စဲ့"}', 5, 6),
  ('{"en":"Shadaw","my":"ရှားတော"}', 5, 7);

-- Kayin State (id=6)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Hlaingbwe","my":"လှိုင်းဘွဲ့"}', 6, 1),
  ('{"en":"Hpa-An","my":"ဘားအံ"}', 6, 2),
  ('{"en":"Hpapun","my":"ဖာပွန်"}', 6, 3),
  ('{"en":"Kawkareik","my":"ကော့ကရိတ်"}', 6, 4),
  ('{"en":"Kyainseikgyi","my":"ကြာအင်းဆိပ်ကြီး"}', 6, 5),
  ('{"en":"Myawaddy","my":"မြဝတီ"}', 6, 6),
  ('{"en":"Thandaunggyi","my":"သံတောင်ကြီး"}', 6, 7);

-- Chin State (id=3)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Falam","my":"ဖလမ်း"}', 3, 1),
  ('{"en":"Hakha","my":"ဟားခါး"}', 3, 2),
  ('{"en":"Htantlang","my":"ထန်တလန်"}', 3, 3),
  ('{"en":"Kanpetlet","my":"ကန်ပက်လက်"}', 3, 4),
  ('{"en":"Madupi","my":"မတူပီ"}', 3, 5),
  ('{"en":"Mindat","my":"မင်းတပ်"}', 3, 6),
  ('{"en":"Paletwa","my":"ပလက်ဝ"}', 3, 7),
  ('{"en":"Tiddim","my":"တီးတိန်"}', 3, 8),
  ('{"en":"Tonzang","my":"တွန်းဇံ"}', 3, 9);

-- Mon State (id=9)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Bilin","my":"ဘီးလင်း"}', 9, 1),
  ('{"en":"Chaungzon","my":"ချောင်းဆုံ"}', 9, 2),
  ('{"en":"Kyaikmaraw","my":"ကျိုက်မရော"}', 9, 3),
  ('{"en":"Kyaikto","my":"ကျိုက်ထို"}', 9, 4),
  ('{"en":"Mawlamyine","my":"မော်လမြိုင်"}', 9, 5),
  ('{"en":"Mudon","my":"မုဒုံ"}', 9, 6),
  ('{"en":"Paung","my":"ပေါင်"}', 9, 7),
  ('{"en":"Thanbyuzayat","my":"သံဖြူဇရပ်"}', 9, 8),
  ('{"en":"Thaton","my":"သထုံ"}', 9, 9),
  ('{"en":"Ye","my":"ရေး"}', 9, 10);

-- Rakhine State (id=11)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Ann","my":"အမ်း"}', 11, 1),
  ('{"en":"Buthidaung","my":"ဘူးသီးတောင်"}', 11, 2),
  ('{"en":"Gwa","my":"ဂွ"}', 11, 3),
  ('{"en":"Kyaukphyu","my":"ကျောက်ဖြူ"}', 11, 4),
  ('{"en":"Kyauktaw","my":"ကျောက်တော်"}', 11, 5),
  ('{"en":"Maungdaw","my":"မောင်တော"}', 11, 6),
  ('{"en":"Minbya","my":"မင်းပြား"}', 11, 7),
  ('{"en":"Mrauk-U","my":"မြောက်ဦး"}', 11, 8),
  ('{"en":"Munaung","my":"မုန်တောင်"}', 11, 9),
  ('{"en":"Myebon","my":"မြေပုံ"}', 11, 10),
  ('{"en":"Pauktaw","my":"ပေါက်တော"}', 11, 11),
  ('{"en":"Ponnagyun","my":"ပုဏ္ဏားကျွန်း"}', 11, 12),
  ('{"en":"Ramree","my":"ရမ်းဗြဲ"}', 11, 13),
  ('{"en":"Rathedaung","my":"ရသေ့တောင်"}', 11, 14),
  ('{"en":"Sittwe","my":"စစ်တွေ"}', 11, 15),
  ('{"en":"Thandwe","my":"သံတွဲ"}', 11, 16),
  ('{"en":"Toungup","my":"တောင်ကုတ်"}', 11, 17);

-- Shan State (id=13)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Hopang","my":"ဟိုပန်"}', 13, 1),
  ('{"en":"Hsihseng","my":"ဆီဆိုင်"}', 13, 2),
  ('{"en":"Hseni","my":"သိန္နီ"}', 13, 3),
  ('{"en":"Hsipaw","my":"သီပေါ"}', 13, 4),
  ('{"en":"Kalaw","my":"ကလော"}', 13, 5),
  ('{"en":"Kengtung","my":"ကျိုင်းတုံ"}', 13, 6),
  ('{"en":"Kunhing","my":"ကွန်ဟိန်း"}', 13, 7),
  ('{"en":"Kunlong","my":"ကွမ်းလုံ"}', 13, 8),
  ('{"en":"Kutkai","my":"ကွတ်ခိုင်"}', 13, 9),
  ('{"en":"Kyaukme","my":"ကျောက်မဲ"}', 13, 10),
  ('{"en":"Laihka","my":"လဲချား"}', 13, 11),
  ('{"en":"Langkho","my":"လင်းခေး"}', 13, 12),
  ('{"en":"Lashio","my":"လားရှိုး"}', 13, 13),
  ('{"en":"Laukkaing","my":"လောက်ကိုင်"}', 13, 14),
  ('{"en":"Lawksawk","my":"ရပ်စောက်"}', 13, 15),
  ('{"en":"Loilen","my":"လွိုင်လင်"}', 13, 16),
  ('{"en":"Mabein","my":"မဘိမ်း"}', 13, 17),
  ('{"en":"Manton","my":"မန်တုံ"}', 13, 18),
  ('{"en":"Mawkmai","my":"မောက်မယ်"}', 13, 19),
  ('{"en":"Monghpyak","my":"မုံးဖျက်"}', 13, 20),
  ('{"en":"Monghsat","my":"မိုင်းဆတ်"}', 13, 21),
  ('{"en":"Mongkhet","my":"မိုင်းခက်"}', 13, 22),
  ('{"en":"Mongmit","my":"မိုးမိတ်"}', 13, 23),
  ('{"en":"Mongpan","my":"မိုင်းပန်"}', 13, 24),
  ('{"en":"Mongping","my":"မိုင်းပျဉ်း"}', 13, 25),
  ('{"en":"Mongton","my":"မိုင်းတုံ"}', 13, 26),
  ('{"en":"Mongyang","my":"မိုင်းယန်း"}', 13, 27),
  ('{"en":"Mongyawng","my":"မိုင်းယောင်း"}', 13, 28),
  ('{"en":"Muse","my":"မူဆယ်"}', 13, 29),
  ('{"en":"Namhsan","my":"နမ့်ဆန်"}', 13, 30),
  ('{"en":"Namtu","my":"နမ္မတူ"}', 13, 31),
  ('{"en":"Nanhkan","my":"နမ့်ခမ်း"}', 13, 32),
  ('{"en":"Nansang","my":"နမ့်စန်"}', 13, 33),
  ('{"en":"Nawnghkio","my":"နောင်ချို"}', 13, 34),
  ('{"en":"Nyaungshwe","my":"ညောင်ရွှေ"}', 13, 35),
  ('{"en":"Pekon","my":"ဖယ်ခုံ"}', 13, 36),
  ('{"en":"Pindaya","my":"ပင်းတယ"}', 13, 37),
  ('{"en":"Pinlaung","my":"ပင်လောင်း"}', 13, 38),
  ('{"en":"Tachileik","my":"တာချီလိတ်"}', 13, 39),
  ('{"en":"Tangyan","my":"တန့်ယန်း"}', 13, 40),
  ('{"en":"Taunggyi","my":"တောင်ကြီး"}', 13, 41),
  ('{"en":"Ywangan","my":"ရွာငံ"}', 13, 42);

-- Naypyitaw Union Territory (id=10)
INSERT INTO public.townships (name, region_id, sort_order) VALUES
  ('{"en":"Dekkhinathiri","my":"ဒက္ခိဏသီရိ"}', 10, 1),
  ('{"en":"Lewe","my":"လယ်ဝေး"}', 10, 2),
  ('{"en":"Ottarathiri","my":"ဥတ္တရသီရိ"}', 10, 3),
  ('{"en":"Pobbathiri","my":"ပုဗ္ဗသီရိ"}', 10, 4),
  ('{"en":"Pyinmana","my":"ပျဉ်းမနား"}', 10, 5),
  ('{"en":"Tatkon","my":"တပ်ကုန်း"}', 10, 6),
  ('{"en":"Zabuthiri","my":"ဇမ္ဗူသီရိ"}', 10, 7),
  ('{"en":"Zeyarthiri","my":"ဇေယျာသီရိ"}', 10, 8);
